### ISSUE TITLE
Pending Hoob in Bot

### ISSUE THREAD

**Issue by mustafamnr** [taha2009/faiz-static#318]
Need list to Hoob whose amount is greater than <certain amount>

For examples, Give me the list of thali whose hoob is greater than 20,000 or 10,000

**Comment by mustafamnr** [comment]
In output, we need
Thali No.
Name 
Mobile
Transporter
Amount pending

**Comment by yusuf4u52** [comment]
Done - Sending just the thali number gives the thali details
